### ISSUE TITLE
Implement Launchpad

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvespace#72]
* [x] DNS Router Changes
* [x] create launchpad user
   * [x] remove from banned usernames
   * [x] `prod`
   * [x] `dev`
* [x] #73
* [x] #77
* [x] #79
